version: "3.3"

services:

  image-fetcher:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5000"
    networks:
      - service-network

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=app
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.1/24"